### ISSUE TITLE
Not working in 3DS Max 2023

### ISSUE THREAD

**Issue by dj0nes** [ptasev/Age-of-Mythology#1]
Thank you for creating and maintaining this plugin!

I see the following error in Max 2023:

```
System.MissingMethodException: Method not found: 'Void ManagedServices.MaxscriptSDK.ExecuteMaxscriptCommand(System.String)'.
   at AoMEngineLibrary.Graphics.Maxscript.Command(String command, Object[] args)
   at AoMEngineLibrary.AMP.MaxPluginForm.importToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Not sure what to make of that. Perhaps a new release would help? I'm running `7.3.0+20190523` as it's the latest version on your [homepage](https://ryder25.com/modding/bang-engine/).

Cheers!

**Comment by ptasev** [comment]
Hey, the plugin is no longer maintained. You can instead use the [AoM Model Editor](https://p2t5r.itch.io/aom-model-editor). This works by using glTF as the intermediary format between the app and modelling tools like Blender and 3ds Max. Blender has built-in support for glTF while 3ds Max needs a plugin. I believe BabylonJS has a plugin for 3ds Max.

**Comment by dj0nes** [comment]
Awesome, Model Editor is working really nicely. Thanks!
